name: Deploy API

on:
  push:
    branches: ["main"]
jobs:
  hop-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Hop
        with:
          token: ${{secrets.HOP_TOKEN}}
        uses: hopinc/action@v1
